fps = 60

verticalTile = 20
TILE_SIZE = 8

ASCREEN_WIDTH, ASCREEN_HEIGHT = 160, verticalTile * TILE_SIZE #SCREEN WHERE EVERYTHING GETS DRAW
SCREEN_WIDTH, SCREEN_HEIGHT = 480, 640 #SCREEN SIZE TO SCALE UP TO


